const reasonsArray = [
    {reason: "Du hast wunderschöne Augen"},
    {reason: "Du hast ein wunderschönes Gesicht"},
    {reason: "Dein Lächeln ist einfach Gold wert"},
    {reason: "Ich liebe einfach deinen Charakter"},
    {reason: "Du hast, denn besten Humor"},
    {reason: "Du bist im Allgemeinen Wunderschön"},
    {reason: "Ich liebe dich über alles"},
    {reason: "Ich kann mit dir stundenlang reden"},
    {reason: "Jedes Mal, wenn ich dich sehe, wird meine Stimmung gleich besser"},
    {reason: "Du bist so ein lebensfroher Mensch"},
    {reason: "Du merkst immer, wenn es mir nicht so gut geht"},
    {reason: "Du merkst, wenn mich etwas stört"},
    {reason: "Du hörts mir immer zu"},
    {reason: "Du bist ein so sozialer Mensch"},
    {reason: "Du verstehst dich einfach mit jedem"},
    {reason: "Du versuchst immer das Beste aus allem zu machen"},
    {reason: "Du kümmerst dich um mich"},
    {reason: "Ich liebe dein Lachen"},
    {reason: "Ich liebe dich für deine Offenheit"},
    {reason: "Mit dir kann ich über alles reden"},
    {reason: "Wenn du mit mir redest, fühle ich mich so sicher"},
    {reason: "Du bist einfach die Beste"},
    {reason: "Du bist wunderschön so wie du bist"},
    {reason: "Dir ist teilweise egal was die anderen sagen"},
    {reason: "In deiner Nähe fühle ich mich viel wohler"},
    {reason: "Ich liebe es wie du mich anschaust"},
    {reason: "Deine Augen funkeln wie Sterne wenn ich sie anstarre"},
    {reason: "Einfach alles ist an dir süß"},
    {reason: "Es ist so süß, wenn du mir nicht in die Augen schauen kannst"},
    {reason: "Jede kleine Geste bedeutet mir einfach so viel"},
    {reason: "Wenn ich etwas mache, wo du dabei bist ist es 100x mal besser"},
    {reason: "Meine Liebe ist unbeschreiblich zu dir"},
    {reason: "Ich liebe es wie du mich küsst"},
    {reason: "Dieses Lächeln was du mir gibts, wenn du mich siehst, ist einfach wunderbar"},
    {reason: "Mit dir fühlen sich stunden wie Minuten an"},
    {reason: "Ich liebe deine Spontanität"},
    {reason: "Wenn ich dich angucke, dann ist mein Kopf wie leer gepustet"},
    {reason: "Bei dir sind meine Ängste einfach wie verschwunden"},
    {reason: "Insgeheim liebe ich es, wenn du mich ärgerst"},
    {reason: "Ich liebe jede Seite an dir"},
    {reason: "Wenn du viel Energie hast dann freue ich mich jedes Mal"},
    {reason: "Ich liebe es, wenn du dich freust"},
    {reason: "Ich bin glücklich, wenn du glücklich bist"},
    {reason: "Ich kann dir jedes Geheimnis anvertrauen"},
    {reason: "Du hast so ein großes Herz"},
    {reason: "Ich liebe D I C H"},
    {reason: "Du vertraust mir"},
    {reason: "Du zeigst auch deine Ängste"},
    {reason: "Ich liebe es, wenn du schwach wirst"},
    {reason: "Ich kann einfach immer Goofy mit dir sein"},
    {reason: "Ich liebe es, wenn wir beide uns wie Quarkköpfe verhalten"},
    {reason: "Du siehst einfach immer wunderschön aus"},
    {reason: "Du hast einfach die schönsten Ohrringe"},
    {reason: "Ich kann mit dir auch ernst reden und du versuchst mir zuzuhören"},
    {reason: "Du hörst mir zu"},
    {reason: "Ich liebe es wie du mir deine Liebe zeigst"},
    {reason: "Du siehst immer richtig süß aus"},
    {reason: "Mit dir kann ich Witze mache die ich mich sonst nicht traue"},
    {reason: "Du glaubst an das gute"},
    {reason: "Du versuchst mir meine Ängste zu nehmen"},
    {reason: "Ich liebe deine Ehrlichkeit"},
    {reason: "Du lässt mich nie alleine"},
    {reason: "Ich denke am Morgen und vor dem Einschlafen an dich"},
    {reason: "Du gibts mir Komplimente, die mir noch nie jemand gegeben hat"},
    {reason: "Du lässt mich immer wissen wie schön du mich findest"},
    {reason: "Ich würde alles stehen und liegen lassen, wenn es dir schlecht geht"},
    {reason: "Bei dir vergesse ich alles um mich herum"},
    {reason: "Du verstehst mich"},
    {reason: "Ich versuche immer das es dir am besten geht"},
    {reason: "Du hast immer die Besten Ideen"},
    {reason: "Ich liebe es wie du mich berührst"},
    {reason: "Weil du mich so akzeptierst wie ich bin"},
    {reason: "Ich liebe es wie wir immer versuchen uns zu sehen, selbst wenn es nur ein paar Minuten ist"},
    {reason: "Ich finde es richtig toll, dass du auch für kitschiges zeug zu haben bist"},
    {reason: "Du hast einfach immer die besten Sprüche drauf"},
    {reason: "Wir schreiben immer, denn ganzen Tag"},
    {reason: "Ich liebe es, wenn ich dir nicht Guten Morgen schreiben muss, sondern sagen kann"},
    {reason: "Du stehst immer hinter mir"},
    {reason: "Ich liebe es, wenn du mir Sachen zeigst die du gerne machst"},
    {reason: "Ich liebe es wenn du mir Sachen zeigst die du interessant findest"},
    {reason: "Ich versuche immer die kleinsten Dinge an dir zu bemerken"},
    {reason: "Ich merke mir einfach alles, was du sagst"},
    {reason: "Ich erinnre mich an jede Situation, die wir haben"},
    {reason: "Ich kann dir nie böse sein"},
    {reason: "Ich liebe es wie du sauer sein willst es aber nicht kannst"},
    {reason: "Ich liebe es, wenn du viel mit mir redest"},
    {reason: "Du kannst so gut erzählen"},
    {reason: "Ich könnte dir stunden zu hören"},
    {reason: "Du gibst mir jedes Mal Schmetterlinge im Bauch"},
    {reason: "Du hast ein Herz aus Gold"},
    {reason: "Dir ist es egal wie ich aussehe"},
    {reason: "Für mich bist du immer wunderschön"},
    {reason: "Egal wann du siehst einfach perfekt aus"},
    {reason: "Du munterst mich immer wieder auf"},
    {reason: "Weil du mir nie absichtlich weh tun würdest"},
    {reason: "Ich finde es süß, wie ich deine Termine besser kann als du"},
    {reason: "Dir ist nichts peinlich vor anderen mit mir"},
    {reason: "Ich finde es süß wie du versuchst unangenehme Dinge nicht unangenehm zu machen"},
    {reason: "Zusammen schaffen wir einfach alles"},
    {reason: "Wir sind einfach soulmates"},
    {reason: "Ich merke, wie ich Sachen von dir übernehme"},
]

let btn = document.getElementById("btn")
btn.addEventListener("click", reasons)

function reasons(){
    const randomIndex = Math.floor(Math.random() * reasonsArray.length)
    const randomItem = reasonsArray[randomIndex]
    document.getElementById("reason").textContent = randomIndex + ": " + randomItem.reason
}

